name: hlfchat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.16
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  google_sign_in: ^5.3.1
  image_picker: ^0.8.5+3
  permission_handler: ^9.2.0
  provider: ^6.0.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
